"""GET /api/demo/scenario, /scenario/meta, /brief and POST /api/demo/rebuild."""
from __future__ import annotations

import json
import os
import time

import pytest

from selene.scenario.demo import SCENARIO_PATH

REQUIRED_KINDS = ("custody_nominal", "maneuver_detected", "custody_degraded", "custody_lost", "reachability_alert", "tasking_update",
                  "custody_regained", "maneuver_characterised", "brief_ready")


@pytest.fixture(autouse=True)
def _use_committed_bundle(monkeypatch):
    monkeypatch.delenv("SELENE_DEMO_SCENARIO", raising=False)


def _first(events, kind):
    return next(e for e in events if e["kind"] == kind)


def test_committed_bundle_served_fast(client):
    assert SCENARIO_PATH.exists(), "data/demo/scenario.json must be committed (python -m selene.scenario.demo --rebuild)"
    assert SCENARIO_PATH.stat().st_size < 15e6
    t = time.perf_counter()
    r = client.get("/api/demo/scenario")
    dt = time.perf_counter() - t
    assert r.status_code == 200, r.text
    d = r.json()
    print(f"/api/demo/scenario: {dt:.2f} s, {SCENARIO_PATH.stat().st_size / 1e6:.2f} MB, frames={len(d['frames'])}, fast={d['meta'].get('fast')}")
    assert dt < 2.0
    assert set(d) >= {"meta", "frames", "events", "metrics", "brief"}
    assert len(d["frames"]) >= 100
    kinds = {e["kind"] for e in d["events"]}
    assert all(k in kinds for k in REQUIRED_KINDS), kinds
    assert d["brief"].startswith("# Analyst brief") and "SIMULATED — notional actor — generated by SELENE at" in d["brief"]
    assert d["meta"]["protagonist_id"] == "SIM-DRO-01"
    # second call is the in-memory cache
    t = time.perf_counter()
    assert client.get("/api/demo/scenario").status_code == 200
    assert time.perf_counter() - t < 2.0


def test_committed_bundle_is_the_full_build_with_the_story(client):
    """The repository copy must be the full (not --fast) build and carry the measured story, not just the shape."""
    d = client.get("/api/demo/scenario").json()
    assert d["meta"]["fast"] is False, "commit the full build: python -m selene.scenario.demo --rebuild"
    m = d["metrics"]
    assert m["dv_est_mps"] is not None and abs(m["dv_est_err_pct"]) < 30.0 and m["dir_err_deg"] < 20.0
    assert m["loss_reason"]["dominant"] == "moon_exclusion" and m["loss_reason"]["at_loss"] == "moon_exclusion"
    assert m["loss_reason"]["n_frames_no_site_available_after_detection"] >= 1   # the honest non-glare hours are counted
    assert m["t_lost_utc"] is not None and m["t_regained_utc"] is not None and m["regained_after_h"] > 0
    ev = d["events"]
    t = {k: _first(ev, k)["t_s"] for k in ("maneuver", "maneuver_detected", "custody_lost", "tasking_update", "custody_regained",
                                            "maneuver_characterised", "brief_ready")}
    assert t["maneuver"] < t["maneuver_detected"] <= t["custody_lost"] < t["tasking_update"] <= t["custody_regained"] \
        < t["maneuver_characterised"] < t["brief_ready"]
    assert [e["t_s"] for e in ev] == sorted(e["t_s"] for e in ev)
    assert m["detection"]["nees_mean"] <= m["detection"]["nees_bounds"][1]       # never over-confident
    assert "sampling resolution" in d["brief"] and "not a glare effect" in d["brief"]


def test_meta_and_brief_endpoints(client):
    r = client.get("/api/demo/scenario/meta")
    assert r.status_code == 200, r.text
    d = r.json()
    assert "meta" in d and "metrics" in d and d["n_frames"] >= 100
    assert d["bundle_bytes"] == SCENARIO_PATH.stat().st_size
    m = d["metrics"]
    for k in ("detection_latency_h", "dv_true_mps", "dv_est_mps", "dv_est_err_pct", "dir_err_deg", "regained_after_h", "custody_timeline", "sigma_timeline"):
        assert k in m, k
    r = client.get("/api/demo/brief")
    assert r.status_code == 200
    assert r.headers["content-type"].startswith("text/markdown")
    assert r.text.startswith("# Analyst brief")


def test_404_with_instructions_when_missing(client, monkeypatch, tmp_path):
    monkeypatch.setenv("SELENE_DEMO_SCENARIO", str(tmp_path / "nope.json"))
    # a stale meta file next to a missing bundle must not turn /meta into a 200
    (tmp_path / "nope_meta.json").write_text(json.dumps({"meta": {"stale": True}, "metrics": {}, "n_frames": 0, "n_events": 0}))
    for url in ("/api/demo/scenario", "/api/demo/scenario/meta", "/api/demo/brief"):
        r = client.get(url)
        assert r.status_code == 404, url
        assert "selene.scenario.demo --rebuild" in r.json()["detail"]


def test_rebuild_fast_then_serve(client, monkeypatch, tmp_path):
    out = tmp_path / "scenario.json"
    monkeypatch.setenv("SELENE_DEMO_SCENARIO", str(out))
    # the route only runs the fast build; the full build is CLI-only
    r = client.post("/api/demo/rebuild", params={"fast": "false"})
    assert r.status_code == 400 and "--rebuild" in r.json()["detail"]
    assert not out.exists()
    t = time.perf_counter()
    r = client.post("/api/demo/rebuild", params={"fast": "true", "seed": 0})
    dt = time.perf_counter() - t
    assert r.status_code == 200, r.text
    d = r.json()
    print(f"rebuild fast: {dt:.1f} s, {d['bundle_bytes'] / 1e6:.2f} MB, headline {d['headline']}")
    assert dt < 90.0 and d["status"] == "ok" and d["fast"] is True
    assert out.exists() and out.with_name("scenario_meta.json").exists()
    assert d["headline"]["dv_est_mps"] is not None and abs(d["headline"]["dv_est_err_pct"]) < 30.0
    r = client.get("/api/demo/scenario")
    assert r.status_code == 200 and r.json()["meta"]["fast"] is True
    meta = json.loads(out.with_name("scenario_meta.json").read_text())
    assert meta["n_frames"] == len(r.json()["frames"])
    assert os.path.getsize(out) == d["bundle_bytes"]
