"""Plain-English analyst brief for the demo scenario — template-based, deterministic, no LLM.

:func:`generate_brief` turns the ``meta`` / ``metrics`` / ``events`` blocks produced by
:mod:`selene.scenario.demo` into a Markdown document: title, bottom line up front (BLUF), event
timeline with UTC stamps, maneuver characterisation (Δv, RTN/VNB components, epoch ± uncertainty),
custody status, reachability summary, sensor-tasking actions, confidence and caveats, and the
mandatory footer ``SIMULATED — notional actor — generated by SELENE at <UTC>``.

Every number is read from the metrics (nothing is invented here); jargon is expanded on first use.
The generator never asserts intent and never uses targeting or engagement language: reachability
is presented as *where the object could be and where to look*.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

__all__ = ["generate_brief", "FOOTER_PREFIX"]

FOOTER_PREFIX = "SIMULATED — notional actor — generated by SELENE at "

_REGION_PLAIN = {
    "l1_gateway": "the Earth-Moon L1 gateway (the low-energy doorway between Earth space and the lunar vicinity)",
    "l2_gateway": "the Earth-Moon L2 gateway (the doorway to the lunar far side and translunar space)",
    "nrho_corridor": "the 9:2 near-rectilinear halo orbit (NRHO) corridor used by the notional allied relay",
    "south_pole_approach": "the lunar south-pole approach volume",
    "llo_shell": "the low-lunar-orbit shell (below 5 000 km altitude)",
    "llo_inner": "low lunar orbit below 500 km",
    "geo_belt_return": "a return path toward the geostationary (GEO) belt",
    "earth_return_escape": "the exterior realm beyond the L2 neck (outside the volume Moon-pointed sensors search)",
    "lunar_impact": "the lunar surface (impact)",
}

_REASON_PLAIN = {
    "moon_exclusion": "lunar glare (the object was too close to the bright Moon on the sky)",
    "daylight": "daylight at the site",
    "low_elevation": "the object being below the site's minimum elevation",
    "too_faint": "the object being fainter than the site's limiting magnitude",
    "in_shadow": "the object being in eclipse",
    "sun_exclusion": "solar exclusion",
    "earth_exclusion": "Earth exclusion",
    "out_of_fov": "the object being outside the field of view",
    "no_site_available": "no site having the object above its elevation limit at night",
}


def _f(x, nd=1, unit="", missing="n/a") -> str:
    if x is None:
        return missing
    try:
        return f"{float(x):,.{nd}f}{unit}"
    except (TypeError, ValueError):
        return str(x)


def _utc(s: Optional[str]) -> str:
    return s if s else "n/a"


def _join(items) -> str:
    items = [str(x) for x in items if x]
    if not items:
        return "no sensor"
    if len(items) == 1:
        return items[0]
    return ", ".join(items[:-1]) + " and " + items[-1]


def _nees_verdict(mean, bounds) -> str:
    try:
        lo, hi = float(bounds[0]), float(bounds[1])
        mean = float(mean)
    except (TypeError, ValueError, IndexError):
        return "not evaluated"
    if mean > hi:
        return "ABOVE the band: the filter is OVER-CONFIDENT (covariance too small — the dangerous failure for custody)"
    if mean < lo:
        return "below the band: the covariance is conservative (larger than the realised errors), which is safe for custody but overstates the uncertainty"
    return "consistent"


def _hm(hours) -> str:
    if hours is None:
        return "n/a"
    h = float(hours)
    if h < 1.0:
        return f"{h * 60:.0f} min"
    return f"{h:.1f} h"


def generate_brief(meta: dict, metrics: dict, events: list[dict], generated_utc: Optional[str] = None) -> str:
    m = metrics
    prot = m.get("protagonist", "SIM-DRO-01")
    relay = m.get("relay", "SIM-NRHO-RELAY-01")
    gen = generated_utc or datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    est = m.get("dv_estimate")
    det = m.get("detection", {})
    reach = m.get("reachability", {})
    task = m.get("tasking", {})
    loss = m.get("loss_reason", {}) or {}
    loss_dom = loss.get("dominant")
    loss_plain = _REASON_PLAIN.get(loss_dom, loss_dom or "no ground site could observe the object")
    lost = m.get("t_lost_utc") is not None
    regained = m.get("t_regained_utc") is not None
    characterised = est is not None

    L: list[str] = []
    L.append(f"# Analyst brief — {meta.get('title', 'Demo scenario')}")
    L.append("")
    L.append(f"**Scenario window:** {_utc(meta.get('t0_utc'))} to {_utc(meta.get('t1_utc'))} (UTC). "
             f"**Object of interest:** {prot}, a SIMULATED medium-size spacecraft of a notional actor in a distant retrograde orbit (DRO) "
             f"about the Moon. **Asset of concern:** {relay}, a SIMULATED relay of a notional allied operator in the 9:2 NRHO.")
    L.append("")
    # ---- BLUF ---------------------------------------------------------------------------
    L.append("## Bottom line up front")
    bluf = []
    bluf.append(f"At {_utc(m.get('t_detect_utc'))} SELENE detected an unannounced maneuver by {prot}: a single ground tracklet from "
                f"{m.get('detect_sensor')} was {_f(m.get('detect_residual_arcsec'), 0)} arcsec off the predicted position (normalised innovation "
                f"squared, NIS, {_f(m.get('detect_nis'), 0)} against a threshold of {_f(det.get('threshold_nis_familywise'), 1)}), "
                f"{_hm(m.get('detection_latency_h'))} after the burn.")
    n_blind = loss.get("n_blind_frames_after_detection")
    n_glare = loss.get("n_frames_available_site_blocked_after_detection")
    n_nosite = loss.get("n_frames_no_site_available_after_detection")
    at_loss_plain = _REASON_PLAIN.get(loss.get("at_loss"), loss.get("at_loss") or "n/a")
    if loss.get("at_loss") == loss_dom:
        at_loss_plain = at_loss_plain.split(" (")[0]   # already expanded once in the same paragraph
    if lost:
        bluf.append(f"The ground network then went blind: in {n_glare} of the {n_blind} blind hours after the detection every site that had the "
                    f"object up at night was stopped by {loss_plain}, and in the other {n_nosite} hours no site had it above its elevation limit "
                    f"at night at all. Custody was declared LOST at {_utc(m.get('t_lost_utc'))} when the position uncertainty exceeded "
                    f"{_f(m.get('filter', {}).get('lost_km'), 0, ' km')} (peak {_f(m.get('max_sigma_km'), 0, ' km')}); at that instant the blocker was "
                    f"{at_loss_plain} at {_join(loss.get('available_sites_at_loss') or []) if loss.get('available_sites_at_loss') else 'no site'}.")
    else:
        bluf.append("Custody was degraded but never fully lost within the window.")
    if regained:
        bluf.append(f"The tasker redirected {_join(task.get('sensor_ids') or [task.get('sensor_id')])} to the reachable-set centroid; the object was "
                    f"re-acquired at {_utc(task.get('t_task_utc'))} and custody was regained at {_utc(m.get('t_regained_utc'))} "
                    f"({_hm(m.get('regained_after_h'))} after the loss).")
    elif task.get("sensor_id"):
        bluf.append(f"{task.get('sensor_id')} re-acquired the object at {_utc(task.get('t_task_utc'))} but the uncertainty did not fall below the custody "
                    f"threshold inside the window (final sigma {_f(m['sigma_timeline'][-1]['sigma_km'], 0, ' km')}).")
    else:
        bluf.append("No space observer could re-acquire the object inside the window; custody remains lost.")
    if characterised:
        bluf.append(f"The maneuver is characterised as a {_f(est['dv_mps'], 2)} ± {_f(est['dv_sigma_mps'], 2)} m/s impulsive burn at "
                    f"{_utc(est['t_burn_utc'])} ± {_f(est['t_burn_sigma_s'], 0, ' s')} ({est['classification'].get('primary', 'burn')}); "
                    f"against the SIMULATED truth of {_f(m.get('dv_true_mps'), 1)} m/s the magnitude error is {_f(m.get('dv_est_err_pct'), 1, ' %')} "
                    f"and the direction error {_f(m.get('dir_err_deg'), 1, '°')}.")
    else:
        bluf.append(f"The maneuver could not be characterised: {m.get('dv_estimate_error')}.")
    nrho = next((r for r in reach.get("regions", []) if r["key"] == "nrho_corridor"), None)
    n_rays = reach.get("n_samples")
    if nrho is not None:
        # a 0-vs-1 ray result flips with the measurement-noise seed at this sampling resolution: both cases read as 'marginal'
        if nrho.get("n_hit"):
            how = (f"is marginal at this sampling resolution: {nrho['n_hit']} of {n_rays} sampled rays reach it, only at the budget limit "
                   f"(at least {_f(nrho.get('min_dv_mps'), 0, ' m/s')}, earliest +{_f(nrho['earliest_h'], 0, ' h')})")
        else:
            how = (f"is not reached by any of the {n_rays} sampled rays within {_f(reach.get('horizon_h'), 0, ' h')} — a result at or below the "
                   f"sampling resolution, so a marginal entry at the budget limit cannot be excluded")
        bluf.append(f"Under the assumed {_f(reach.get('dv_budget_mps'), 0, ' m/s')} budget the relay's NRHO corridor {how}; "
                    f"recommendation: keep elevated custody on {prot} and run conjunction screening for {relay}. No intent is inferred.")
    L.extend(f"- {b}" for b in bluf)
    L.append("")
    # ---- timeline ------------------------------------------------------------------------
    L.append("## Timeline (UTC)")
    keep = {"custody_nominal", "maneuver", "maneuver_detected", "custody_degraded", "custody_lost", "reachability_alert",
            "tasking_update", "custody_regained", "entered_region", "maneuver_characterised", "brief_ready"}
    for e in events:
        if e.get("kind") in keep or (e.get("kind") == "observation" and e.get("data", {}).get("reacquired")):
            L.append(f"- `{e.get('t_utc', '')}` **{e.get('kind')}** — {e.get('text')}")
    L.append("")
    # ---- maneuver characterisation ---------------------------------------------------------
    L.append("## Maneuver characterisation")
    if characterised:
        rtn = est["dv_rtn_mps"]
        vnb = est["dv_vnb_mps"]
        L.append(f"- Δv magnitude: **{_f(est['dv_mps'], 2)} ± {_f(est['dv_sigma_mps'], 2)} m/s** (1-sigma). SIMULATED truth: {_f(m.get('dv_true_mps'), 2)} m/s "
                 f"→ error {_f(m.get('dv_est_err_pct'), 1, ' %')}.")
        L.append(f"- Direction (1-sigma {_f(est['direction_sigma_deg'], 1, '°')}; {_f(m.get('dir_err_deg'), 1, '°')} from truth), {est['frame_center']}-centred frames:")
        L.append(f"  - RTN (radial / transverse ≈ along-track / normal): {_f(rtn[0], 1)} / {_f(rtn[1], 1)} / {_f(rtn[2], 1)} m/s "
                 f"(truth {_f(m['dv_true_rtn_mps'][0], 1)} / {_f(m['dv_true_rtn_mps'][1], 1)} / {_f(m['dv_true_rtn_mps'][2], 1)}).")
        L.append(f"  - VNB (velocity / normal / bi-normal): {_f(vnb[0], 1)} / {_f(vnb[1], 1)} / {_f(vnb[2], 1)} m/s "
                 f"(truth {_f(m['dv_true_vnb_mps'][0], 1)} / {_f(m['dv_true_vnb_mps'][1], 1)} / {_f(m['dv_true_vnb_mps'][2], 1)}).")
        L.append(f"- Burn epoch: **{_utc(est['t_burn_utc'])} ± {_f(est['t_burn_sigma_s'], 0, ' s')}** (truth {_utc(m.get('t_burn_utc'))}, "
                 f"error {_f(est['t_burn_err_s'], 0, ' s')}); the burn is only known to lie between the last pre-burn tracklet and the flagged one.")
        L.append(f"- Fit: {est['n_obs']} post-burn angle pairs, residual RMS {_f(est['residual_rms_arcsec'], 2)} arcsec, reduced chi-square "
                 f"{_f(est['reduced_chi2'], 2)}, converged: {est['converged']}.")
        L.append(f"- Descriptive classification (heuristic, no intent): {est['classification'].get('primary')}; "
                 + "; ".join(est['classification'].get('labels', [])[:4]) + ".")
    else:
        L.append(f"- Not characterised: {m.get('dv_estimate_error')}.")
    L.append("")
    # ---- custody -------------------------------------------------------------------------
    L.append("## Custody status")
    cnt = m.get("custody_status_counts", {})
    L.append(f"- Over the {len(m.get('custody_timeline', []))} hourly frames {prot} was in CUSTODY {cnt.get('CUSTODY', 0)} h, DEGRADED {cnt.get('DEGRADED', 0)} h, "
             f"LOST {cnt.get('LOST', 0)} h ({_f(m.get('custody_pct'), 1, ' %')} custody). Thresholds on the particle-cloud position sigma: "
             f"< {_f(m.get('filter', {}).get('custody_km'), 0, ' km')} CUSTODY, > {_f(m.get('filter', {}).get('lost_km'), 0, ' km')} LOST.")
    L.append(f"- Position sigma at detection {_f(m.get('sigma_at_detection_km'), 0, ' km')}; peak {_f(m.get('max_sigma_km'), 0, ' km')} at "
             f"{_utc(m.get('t_max_sigma_utc'))}; after regain {_f(m.get('sigma_after_regain_km'), 1, ' km')}.")
    L.append(f"- Loss mechanism: {loss_plain} ({n_glare} of {n_blind} blind hours after the detection; in the other {n_nosite} hours no site had the object "
             f"above its elevation limit at night, which is not a glare effect). At the loss epoch the blocker was {at_loss_plain}; Moon "
             f"{_f(100 * (m.get('moon_illum_at_loss') or 0), 0, ' %')} illuminated and the object {_f(m.get('moon_sep_deg_at_loss'), 1, '°')} from it on the sky. "
             f"Hourly blind-reason counts between detection and loss: "
             + ", ".join(f"{k} ×{v}" for k, v in (loss.get("counts_between_detection_and_loss") or {}).items())
             + "; detection to end of window: " + ", ".join(f"{k} ×{v}" for k, v in (m.get("ground_blind_reason_counts") or {}).items()) + ".")
    obs = m.get("observations", {})
    L.append(f"- Observations used: {obs.get('n_total')} ({obs.get('n_ground_pre_burn')} ground pre-burn, {obs.get('n_ground_post_burn')} ground post-burn, "
             f"{obs.get('n_space_followup')} space-observer follow-ups); by sensor: "
             + ", ".join(f"{k} {v}" for k, v in (obs.get("by_sensor") or {}).items()) + ".")
    oc = m.get("other_objects_custody", {})
    if oc:
        worst = sorted(oc.items(), key=lambda kv: kv[1]["custody_pct"])[:3]
        L.append(f"- Other catalogued SIMULATED objects (space-observer tasking, linear covariance): lowest custody "
                 + ", ".join(f"{k} {_f(v['custody_pct'], 0, ' %')}" for k, v in worst) + ".")
    L.append("")
    # ---- reachability --------------------------------------------------------------------
    L.append("## Reachability (where it could be — awareness and traffic safety only)")
    L.append(f"- Computed from the last good estimate ({_utc(reach.get('t_ref_utc'))}) with an **assumed** {_f(reach.get('dv_budget_mps'), 0, ' m/s')} budget over "
             f"{_f(reach.get('horizon_h'), 0, ' h')}: {reach.get('n_samples')} sampled impulsive burns ({reach.get('n_dirs')} directions × magnitude ladder × "
             f"{len(reach.get('burn_epochs_h', []))} burn epochs spanning the detection gap).")
    for r in reach.get("regions", []):
        if not (r.get("n_hit") or r.get("nominal_hits")):
            continue
        plain = _REGION_PLAIN.get(r["key"], r["name"])
        if r.get("nominal_hits"):
            L.append(f"- {plain}: already on the unperturbed path (first entry +{_f(r.get('earliest_nominal_h'), 0, ' h')} with no burn"
                     + (f"; earliest +{_f(r.get('earliest_h'), 0, ' h')} over the sampled burns" if r.get('earliest_h') is not None else "") + ").")
        else:
            L.append(f"- {plain}: {_f(100 * r['fraction'], 1, ' %')} of sampled rays, earliest arrival +{_f(r.get('earliest_h'), 0, ' h')}, "
                     f"minimum Δv to reach ≈ {_f(r.get('min_dv_mps'), 0, ' m/s')}.")
    unreached = [_REGION_PLAIN.get(r["key"], r["name"]) for r in reach.get("regions", []) if not (r.get("n_hit") or r.get("nominal_hits"))]
    if unreached:
        L.append(f"- Not reachable within budget and horizon: " + "; ".join(unreached) + ".")
    tg = m.get("truth_geometry", {})
    L.append(f"- SIMULATED truth for reference: closest approach to L1 {_f(tg.get('min_dist_to_L1_km'), 0, ' km')} at {_utc(tg.get('t_min_dist_to_L1_utc'))}; "
             f"closest approach to {relay} {_f(tg.get('min_dist_to_relay_km'), 0, ' km')} at {_utc(tg.get('t_min_dist_to_relay_utc'))}.")
    L.append("")
    # ---- tasking -------------------------------------------------------------------------
    L.append("## Sensor tasking actions")
    if task.get("sensor_id"):
        L.append(f"- {task['sensor_id']} redirected at {_utc(task.get('t_task_utc'))} to RA {_f(task.get('pointing_ra_deg'), 2, '°')}, "
                 f"Dec {_f(task.get('pointing_dec_deg'), 2, '°')} (centroid of the reachable set as seen from the sensor), "
                 f"{task.get('n_fields_used')} field(s) searched (mosaic radius {_f(task.get('mosaic_radius_deg'), 2, '°')}; {task.get('n_fields')} would cover "
                 f"the full 90th-percentile spread of {_f(task.get('spread_p90_deg'), 2, '°')}); "
                 f"the SIMULATED truth was {_f(task.get('offset_deg'), 2, '°')} from the boresight at range {_f(task.get('range_km'), 0, ' km')}, "
                 f"predicted magnitude {_f(task.get('magnitude'), 1)}.")
        others_s = [r for r in task.get("sensors", []) if r.get("sensor_id") != task.get("sensor_id")]
        if others_s:
            L.append("- Also tasked in the same slot and verified against truth: " + "; ".join(
                f"{r['sensor_id']} ({r.get('n_fields_used')} of {r.get('n_fields_p90')} field(s), p90 spread {_f(r.get('spread_p90_deg'), 2, '°')}, range {_f(r.get('range_km'), 0, ' km')}, "
                f"truth {_f(r.get('offset_deg'), 2, '°')} from boresight, magnitude {_f(r.get('magnitude'), 1)})" for r in others_s) + ".")
        for b in task.get("blocked", []) or []:
            L.append(f"- Not tasked: {b['sensor_id']} — {_REASON_PLAIN.get(b.get('reason'), b.get('reason') or 'no visibility')}.")
        L.append(f"- Scheduler: {task.get('scheduler')}, search budget {task.get('search_tiles_used_by_scheduler')} fields per slot (shared by the "
                 f"scheduler's acquisition model and the truth verification), "
                 f"{_hm(task.get('escalation_delay_h'))} re-planning latency; "
                 f"{task.get('n_followup_obs')} follow-up tracklets at the follow-up cadence; {len(task.get('attempts', []))} tasked look(s) evaluated against truth.")
    else:
        L.append(f"- No successful re-acquisition; {len(task.get('attempts', []))} tasked look(s) evaluated against truth.")
    segs = m.get("tasking_segments", {})
    for key, s in segs.items():
        if s:
            L.append(f"- Routine schedule segment {key}: {s.get('n_objects')} objects, {s.get('n_sensors')} space observers, {s.get('n_observations')} looks over "
                     f"{_f(s.get('horizon_h'), 0, ' h')}, custody {_f(s.get('custody_pct'), 0, ' %')}, mean time since last observation {_hm(s.get('mean_tslo_h'))}.")
    L.append("")
    # ---- confidence / caveats -------------------------------------------------------------
    L.append("## Confidence and caveats")
    L.append(f"- Detection test: per-update NIS against a chi-square threshold with per-test false-alarm probability alpha = {det.get('alpha')} "
             f"(family-wise over the run: NIS threshold {_f(det.get('threshold_nis_familywise'), 1)}); {det.get('n_tested')} of {det.get('n_updates')} updates tested, "
             f"run status '{det.get('status')}'.")
    nm = det.get("nees_mean")
    nb = det.get("nees_bounds") or [None, None]
    L.append(f"- Covariance realism (simulation-only, needs truth): mean normalised estimation error squared (NEES) {_f(nm, 2)} over {det.get('nees_n_epochs')} epochs "
             f"against the 95 % band [{_f(nb[0], 2)}, {_f(nb[1], 2)}] for 6 degrees of freedom → {_nees_verdict(nm, nb)}; "
             f"baseline (pre-burn) mean NEES {_f(det.get('nees_baseline_mean'), 2)} vs the over-confidence bound {_f(det.get('nees_baseline_bound'), 2)}. "
             "Successive errors of one run are correlated, so the band is indicative; the Monte-Carlo NEES study lives in the OD module's tests.")
    for w in det.get("warnings", []) or []:
        L.append(f"- Filter warning: {w}")
    L.append(f"- After the detection the filter prior was re-opened for an impulsive Δv of 1-sigma {_f(m.get('filter', {}).get('reopen_sigma_dv_mps'), 0, ' m/s')} "
             f"at an unknown epoch in the last gap; this assumption must bound the burn class or the filter would be over-confident.")
    L.append(f"- Reachability fractions are fractions of sampled (direction, epoch) rays under an assumed budget; they are not probabilities of any action and assert no intent.")
    for a in meta.get("assumptions", []):
        L.append(f"- Assumption: {a}")
    L.append("")
    L.append("---")
    L.append(FOOTER_PREFIX + gen)
    return "\n".join(L)
